// Code generated by Kitex v0.7.1. DO NOT EDIT.

package userinfoservice

import (
	"context"
	userinfo "dousheng/userinfo/kitex_gen/userinfo"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return userInfoServiceServiceInfo
}

var userInfoServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "UserInfoService"
	handlerType := (*userinfo.UserInfoService)(nil)
	methods := map[string]kitex.MethodInfo{
		"GetUserInfo": kitex.NewMethodInfo(getUserInfoHandler, newUserInfoServiceGetUserInfoArgs, newUserInfoServiceGetUserInfoResult, false),
	}
	extra := map[string]interface{}{
		"PackageName":     "userinfo",
		"ServiceFilePath": "../dousheng_idl/userinfo/userinfo.thrift",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.7.1",
		Extra:           extra,
	}
	return svcInfo
}

func getUserInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*userinfo.UserInfoServiceGetUserInfoArgs)
	realResult := result.(*userinfo.UserInfoServiceGetUserInfoResult)
	success, err := handler.(userinfo.UserInfoService).GetUserInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserInfoServiceGetUserInfoArgs() interface{} {
	return userinfo.NewUserInfoServiceGetUserInfoArgs()
}

func newUserInfoServiceGetUserInfoResult() interface{} {
	return userinfo.NewUserInfoServiceGetUserInfoResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetUserInfo(ctx context.Context, req *userinfo.UesrInfoRequest) (r *userinfo.UserInfoResponse, err error) {
	var _args userinfo.UserInfoServiceGetUserInfoArgs
	_args.Req = req
	var _result userinfo.UserInfoServiceGetUserInfoResult
	if err = p.c.Call(ctx, "GetUserInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
