Configs:
  # MysqlConfig:
  #   URL: "root:123456@tcp(mysql:3306)/dousheng?charset=utf8&parseTime=True&loc=Local"

  # MogoDBConfig:
  #   URI: "mongodb://root:123456@mongo:27017"

  EtcdConfig:
    Endpoints:
      - "Etcd:2379"
  
  # RpcConfig:
  #   ServiceNetwork: "tcp"
  #   ServiceAddress: "0.0.0.0:8889"

  JaegerConfig:
    Disabled: false
    Sampler:
      Type: "const"
      Param: 1
      SamplingServerURL: "http://jaeger:5778/sampling"
    Reporter:
      LogSpans: true
      LocalAgentHostPort : "jaeger:6831"

  HertzConfig:
    MaxRequestBodySizeMB: 20
    HostPorts: "0.0.0.0:8888"

  MinioConfig:
    Endpoint: "minio:9000"
    AccessKeyID: "minioadmin"
    SecretAccessKey: "minioadmin"
    UseSSL: false
    Region: "local"
    MinioAccessUrl: "127.0.0.1:9000"
      

