static_resources:
  listeners:
  - name: redis_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 1999
    filter_chains:
    - filters:
      - name: envoy.filters.network.redis_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProxy
          stat_prefix: egress_redis
          settings:
            # op_timeout: 5s
            op_timeout: 1s
            max_buffer_size_before_flush: 1024
            buffer_flush_timeout: 0.003s
          prefix_routes:
            catch_all_route:
              cluster: redis_cluster
          downstream_auth_passwords:
            - inline_string: "bar"
  clusters:
  - name: redis_cluster
    cluster_type:
      name: envoy.clusters.redis
    lb_policy: CLUSTER_PROVIDED
    load_assignment:
      cluster_name: redis_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: redis-1
                port_value: 6379
        - endpoint:
            address:
              socket_address:
                address: redis-2
                port_value: 6379
        - endpoint:
            address:
              socket_address:
                address: redis-3
                port_value: 6379
        - endpoint:
            address:
              socket_address:
                address: redis-4
                port_value: 6379
        - endpoint:
            address:
              socket_address:
                address: redis-5
                port_value: 6379
        - endpoint:
            address:
              socket_address:
                address: redis-6
                port_value: 6379
    typed_extension_protocol_options:
      envoy.filters.network.redis_proxy:
        "@type": type.googleapis.com/google.protobuf.Struct
        value:
          auth_password:
            inline_string: "123456"
admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001