// Code generated by hertz generator.

package first

import (
	"context"

	handler "dousheng/router/biz/handler"
	core "dousheng/router/biz/handler/core"
	first "dousheng/router/biz/model/extra/first"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// FavoriteActionHandler .
// @router /douyin/favorite/action/ [POST]
func FavoriteActionHandler(ctx context.Context, c *app.RequestContext) {
	var err error
	var req first.DouyinFavoriteActionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(first.DouyinFavoriteActionResponse)

	var failStatusCode int32 = 1
	var failStatusMsg = "User doesn't exist"

	if _, exist := core.UsersLoginInfo[*req.Token]; exist {
		resp.StatusCode = new(int32)
	} else {
		resp.StatusCode = &failStatusCode
		resp.StatusMsg = &failStatusMsg
	}

	c.JSON(consts.StatusOK, resp)
}

// FavoriteListHandler .
// @router /douyin/favorite/list/ [GET]
func FavoriteListHandler(ctx context.Context, c *app.RequestContext) {
	var err error
	var req first.DouyinFavoriteListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(first.DouyinFavoriteListResponse)

	resp.StatusCode = new(int32)

	resp.VideoList = handler.DemoVideos

	c.JSON(consts.StatusOK, resp)
}
