// Code generated by hertz generator.

package core

import (
	"context"

	handler "dousheng/router/biz/handler"
	core "dousheng/router/biz/model/core"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// FeedHandler .
// @router /douyin/feed/ [GET]
func FeedHandler(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core.DouyinFeedRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(core.DouyinFeedResponse)
	resp.StatusCode = new(int32)
	resp.VideoList = handler.DemoVideos
	c.JSON(consts.StatusOK, resp)
}
